# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CreateFishnet.py
# Created on: 2015-11-16 11:11:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


CellSize = sys.argv[1]

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "G:\\local\\user projects\\mreardon\\lakes\\SBA MAP2_Lakes_2016_West_11_9_15_subset\\SBA.gdb"
arcpy.env.outputCoordinateSystem = "PROJCS['NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',750000.0],PARAMETER['Central_Meridian',-71.5],PARAMETER['Standard_Parallel_1',41.71666666666667],PARAMETER['Standard_Parallel_2',42.68333333333333],PARAMETER['Latitude_Of_Origin',41.0],UNIT['Meter',1.0]]"
arcpy.env.geographicTransformations = ""
arcpy.env.workspace = "G:\\local\\user projects\\mreardon\\lakes\\SBA MAP2_Lakes_2016_West_11_9_15_subset\\SBA.gdb"


# Local variables:
SBA_gdb = "G:\\local\\user projects\\mreardon\\lakes\\SBA MAP2_Lakes_2016_West_11_9_15_subset\\SBA.gdb"


arcpy.AddMessage("Listing Feature Classes")
#inList = arcpy.ListFeatureClasses()
# Process: Iterate Feature Classes
fcs =arcpy.ListFeatureClasses()


arcpy.AddMessage("Run Fishnet on each feature class")

# code from http://gis.stackexchange.com/questions/113469/creating-fishnet-from-template-feature-class-using-arcpy, user: radouxju
#desc = arcpy.Describe(fc)
#arcpy.CreateFishnet_management(fc[:-4]+"_c200.shp",str(desc.extent.lowerLeft),str(desc.extent.XMin) + " " + str(desc.extent.YMax + 10),"200","200","0","0",str(desc.extent.upperRight),"NO_LABELS","#","POLYGON")

for fc in fcs:
    #set the output name
    Output_Feature_Class = fc +"_"+ CellSize +'meter_fishnet.shp'
    arcpy.AddMessage(Output_Feature_Class)

    #get the feature class extent
    desc = arcpy.Describe(fc)
    
    # Process: Create Fishnet
    arcpy.AddMessage("Creating fishnet for: " + fc)
      #origin
    X1 = float(desc.extent.XMin) - (float(CellSize) / 10.0)
    Y1 = float(desc.extent.YMin) - (float(CellSize) / 10.0)
     #upper right corner
    X2 = float(desc.extent.upperRight.X) +float(CellSize)
    Y2 = float(desc.extent.upperRight.Y) + float(CellSize)
      #create fishnet
    arcpy.AddMessage(str(desc.extent.XMin - 50) + " " + str(desc.extent.YMin -50) + ":" + str(desc.extent.XMin) + " " + str(desc.extent.YMax + 10))
    arcpy.CreateFishnet_management(Output_Feature_Class, str(X1) + " " + str(Y1), str(desc.extent.XMin) + " " + str(desc.extent.YMax + 10), CellSize, CellSize, "0","0",str(X2)+ " " +str(Y2),"NO_LABELS",fc, "POLYLINE")

